# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Build Python Exe

on:
  push:
    branches:
    - main
    # - release/*

permissions:
  actions: write

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - name: build exe with pyinstaller
      shell: bash
      run: |
        python -m pip install --upgrade pip 
        pip install pygame pyYAML
        pip install pyinstaller
        pyinstaller -w -p ./src --add-data ./src/*:./src --icon ./src/main.icns --onefile main.py -n CountDown
        # chmod -R 0755 ./dist
        chown -R $(whoami) ./dist
        # rm -f ./dist/CountDown
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Count_Down_linux
        path: dist
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: build exe with pyinstaller
        shell: bash
        run: |
          python -m pip install --upgrade pip 
          pip install pygame pyYAML
          pip install pyinstaller
          pyinstaller -w -p ./src/ --add-data './src/*;./src' --icon ./src/main.ico --onefile ./main.py -n CountDown
          # chown -R $(stat -c '%u:%g' .) .\dist\
          # del ./dist/CountDown
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Count_Down_exe
          path: dist
  build_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: build exe with pyinstaller
        shell: bash
        run: |
          python -m pip install --upgrade pip 
          pip install pygame pyYAML
          pip install pyinstaller
          pyinstaller -w -p ./src --add-data './src/*':./src --icon ./src/main.icns --onefile main.py -n CountDown
          # chmod -R 0755 ./dist
          chown -R $(whoami) ./dist
          rm -f ./dist/CountDown
          chmod 0777 ./dist/CountDown.app/Contents/MacOS/CountDown
          pip install dmgbuild
          dmgbuild -s ./mycal.dmg.json CountDown ./dist/Math\ Quiz.dmg
          rm -r ./dist/Math\ Quiz.app
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Count_Down_mac
          path: dist
  # release:
      # runs-on: ubuntu-latest
      # needs:
      #   - build_linux
      #   - build_windows
      #   - build_macOS
      # steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     files: dist/*
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: TODO New Release.
      #     draft: false
      #     prerelease: false

      # - name: Create Release
      #   id: create_release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: dist/*
      #     title: Release ${{ github.event.workflow_run.conclusion }}
      #     body: |
      #       Changes in this release:
      #       - Add feature X
      #       - Fix bug Y
      #     token: ${{ secrets.GITHUB_TOKEN }}
